language: php

php:
  - 5.3
  - 5.4

sudo: false

dist: precise

env:
  - DB=MYSQL CORE_RELEASE=3.7

matrix:
  include:
    - php: 5.5
      env: DB=PGSQL CORE_RELEASE=3
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3.7

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install

script:
  - vendor/bin/phpunit sharedraftcontent/tests
